import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { Download, FileText } from 'lucide-react'

import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { reportMarkdown } from '@/lib/mock-data'

export default function ReportsPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-accent">
            <FileText className="h-4 w-4 text-accent-foreground" />
          </div>
          <div>
            <p className="text-sm font-medium text-foreground">Decision brief</p>
            <p className="text-xs text-muted-foreground">Generated by the Writer agent · just now</p>
          </div>
          <Badge variant="success" className="ml-2">
            Final
          </Badge>
        </div>
        <Button size="sm" variant="secondary" className="gap-1.5">
          <Download className="h-3.5 w-3.5" />
          Export PDF
        </Button>
      </div>

      <Card className="p-8 sm:p-10">
        <article
          className="prose prose-invert prose-sm max-w-none
            prose-headings:font-semibold prose-headings:tracking-tight prose-headings:text-foreground
            prose-h1:text-2xl prose-h1:mb-2 prose-h2:text-lg prose-h2:mt-8 prose-h2:mb-3
            prose-p:leading-relaxed prose-p:text-muted-foreground
            prose-strong:text-foreground
            prose-a:text-primary prose-a:no-underline hover:prose-a:underline
            prose-blockquote:border-l-warning/50 prose-blockquote:bg-warning/5 prose-blockquote:py-1 prose-blockquote:not-italic prose-blockquote:text-foreground/80
            prose-li:text-muted-foreground
            prose-hr:border-border"
        >
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{reportMarkdown}</ReactMarkdown>
        </article>
      </Card>
    </div>
  )
}
