import enum

from sqlalchemy import Enum, Float, ForeignKey, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.database.base import Base, TimestampMixin, generate_uuid


class TraceType(str, enum.Enum):
    CHAT = "chat"
    SKILL = "skill"
    EMBEDDING = "embedding"
    MEMORY_EXTRACTION = "memory_extraction"
    TOOL_CALL = "tool_call"
    EVALUATION = "evaluation"


class TraceStatus(str, enum.Enum):
    SUCCESS = "success"
    ERROR = "error"
    TIMEOUT = "timeout"
    RETRIED = "retried"
    DEGRADED = "degraded"


class Trace(Base, TimestampMixin):
    __tablename__ = "traces"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    trace_id: Mapped[str] = mapped_column(String(36), index=True, nullable=False)
    workspace_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("workspaces.id", ondelete="SET NULL"), index=True, nullable=True
    )
    user_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("users.id", ondelete="SET NULL"), index=True, nullable=True
    )
    conversation_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("conversations.id", ondelete="SET NULL"), index=True, nullable=True
    )
    message_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("messages.id", ondelete="SET NULL"), index=True, nullable=True
    )
    # Links this trace back to the evaluation run/case that produced it, when
    # it was generated by the evaluation harness rather than live user
    # traffic — set by evaluation/runner.py after locating the trace for a
    # case, not threaded through every record_trace() call site. Deliberately
    # not folded into `trace_type` (chat/skill/tool_call describe *what*
    # operation ran; this describes *who* triggered it — two different axes).
    evaluation_run_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("evaluation_runs.id", ondelete="SET NULL"), index=True, nullable=True
    )
    eval_case_id: Mapped[str | None] = mapped_column(String(100), index=True, nullable=True)
    trace_type: Mapped[TraceType] = mapped_column(Enum(TraceType), nullable=False, index=True)
    provider: Mapped[str | None] = mapped_column(String(50), nullable=True)
    model: Mapped[str | None] = mapped_column(String(100), nullable=True)
    input_tokens: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    output_tokens: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    cost_usd: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    latency_ms: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    status: Mapped[TraceStatus] = mapped_column(
        Enum(TraceStatus), default=TraceStatus.SUCCESS, nullable=False, index=True
    )
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    retry_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    meta: Mapped[dict | None] = mapped_column(JSON, nullable=True)
